config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
    controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  
  get 'store/index'
  get 'store/about'
  resources :products do
  	get :who_bought, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'store#index', as: 'store', via: :all
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Come&Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body class='<%= controller.controller_name %>'>

    <div id="container">

<div class="container">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar2">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to (image_tag "come.png", class: "navbar-brand"), store_path%>
        
      </div>
      <div id="navbar2" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", store_path%></li>
          <li><%= link_to "About us", store_about_path%></li>
          <li><%= link_to " ", new_order_path, class: "glyphicon glyphicon-shopping-cart"%></li>

          <% if @cart %>
            <li id="logo"><% render("carts/cart_logo")%><%= @logo %></li>
          <% end %>
          
          <% if session[:user_id] %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Orders', orders_path %></li>
              <li><%= link_to 'Products', products_path %></li>
              <li><%= link_to 'Users', users_path%></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            </ul>
          </li>
          <% end %>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
    <!--/.container-fluid -->
  </nav>
</div>

       
      <div id="main" class="container">
        <%= yield %>
      </div>
    </div>

        <!-- Footer -->
<footer class="container">
            <div class="col-xs">              
              <ul class="social-link">
                <li><a href="https://www.linkedin.com/in/ahmed-mamduh" target="_blank" ><span class="fa fa-linkedin"></span></a></li>
                <li><a href="https://github.com/AhmedMamduh" target="_blank" ><span class="fa fa-github"></span></a></li>
              </ul>             
            </div>
 
            <div class="col-xs">
              <div class="copyright-text">
                <p>Come&Shop © Copyright 2018</p>
              </div>
            </div>
  </footer>
  <!-- Footer -->

  
  </body>
</html>